/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ListImport } from './routes/list'
import { Route as IndexImport } from './routes/index'
import { Route as ListIndexImport } from './routes/list.index'
import { Route as ListIdImport } from './routes/list.$id'

// Create/Update Routes

const ListRoute = ListImport.update({
  id: '/list',
  path: '/list',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ListIndexRoute = ListIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ListRoute,
} as any)

const ListIdRoute = ListIdImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ListRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/list': {
      id: '/list'
      path: '/list'
      fullPath: '/list'
      preLoaderRoute: typeof ListImport
      parentRoute: typeof rootRoute
    }
    '/list/$id': {
      id: '/list/$id'
      path: '/$id'
      fullPath: '/list/$id'
      preLoaderRoute: typeof ListIdImport
      parentRoute: typeof ListImport
    }
    '/list/': {
      id: '/list/'
      path: '/'
      fullPath: '/list/'
      preLoaderRoute: typeof ListIndexImport
      parentRoute: typeof ListImport
    }
  }
}

// Create and export the route tree

interface ListRouteChildren {
  ListIdRoute: typeof ListIdRoute
  ListIndexRoute: typeof ListIndexRoute
}

const ListRouteChildren: ListRouteChildren = {
  ListIdRoute: ListIdRoute,
  ListIndexRoute: ListIndexRoute,
}

const ListRouteWithChildren = ListRoute._addFileChildren(ListRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/list': typeof ListRouteWithChildren
  '/list/$id': typeof ListIdRoute
  '/list/': typeof ListIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/list/$id': typeof ListIdRoute
  '/list': typeof ListIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/list': typeof ListRouteWithChildren
  '/list/$id': typeof ListIdRoute
  '/list/': typeof ListIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/list' | '/list/$id' | '/list/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/list/$id' | '/list'
  id: '__root__' | '/' | '/list' | '/list/$id' | '/list/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ListRoute: typeof ListRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ListRoute: ListRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/list"
      ]
    },
    "/": {
      "filePath": "index.jsx"
    },
    "/list": {
      "filePath": "list.jsx",
      "children": [
        "/list/$id",
        "/list/"
      ]
    },
    "/list/$id": {
      "filePath": "list.$id.jsx",
      "parent": "/list"
    },
    "/list/": {
      "filePath": "list.index.jsx",
      "parent": "/list"
    }
  }
}
ROUTE_MANIFEST_END */
